apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: tkn-itlusions-com
spec:
  secretName: tkn-itlusions-com-tls
  issuerRef:
    name: letsencrypt-issuer
    kind: ClusterIssuer
  commonName: tkn.itlusions.com
  dnsNames:
    - tkn.itlusions.com
    - tkn.itlusions.nl